### ISSUE TITLE
Symfony 6.0 support

### ISSUE THREAD

**Issue by kissifrot** [Meteo-Concept/hcaptcha-bundle#10]
Hello,

Is there a symfony 6.x support planned? 
Right now composer.json version  constraints prevent installation but looks like code is compatible (I can provide help for tests if needed :) )

**Comment by lgeorget** [comment]
The code is ready for 6.x but the problem is that the testing dependencies are not so I can't make the automatic tests pass for the moment.

**Comment by kissifrot** [comment]
From what I saw `nyholm/symfony-bundle-test` and `matthiasnoback/symfony-dependency-injection-test` (as well as `symfony/panther`) are now compatiblle 👍

**Comment by quentint** [comment]
Interested in this, too 😉

**Comment by lgeorget** [comment]
Currently I'm a bit stuck by this for the moment: https://github.com/SymfonyTest/symfony-bundle-test/issues/65
`nyholm/symfony-bundle-test` claims to be compatible with Symfony 6 but it's not right now. They should release a new version soone though.

**Comment by lgeorget** [comment]
You can use "meteo-concept/hcaptcha-bundle: dev-v3" in composer.json for now if you want to try out Symfony 6.

**Comment by quentint** [comment]
Good to know, thank you!

**Comment by lgeorget** [comment]
I've released v3.2.0 (https://github.com/Meteo-Concept/hcaptcha-bundle/releases/tag/v3.2.0) with support for Symfony 6.
