### ISSUE TITLE
Support psr/http-message 2.0

### ISSUE THREAD

**Issue by thelem** [Meteo-Concept/hcaptcha-bundle#15]
Composer.json restricts psr/http-message to (^1.0).

2.0 just added return types, so is likely to be an easy upgrade. https://github.com/php-fig/http-message/releases/tag/2.0

This will ensure the module is compatible with other modules that require at least 2.0 of http-message.

**Comment by lgeorget** [comment]
Thank you for bringing that issue to my attention. I need to check that it doesn't introduce a breaking change (it shouldn't but...) and I'll update the composer.json.

**Comment by lgeorget** [comment]
Fixed by commit bb4e5695e9805e55d231632ed4c28e9557910b05
Thank you!

**Comment by thelem** [comment]
Thanks for the super-quick work.
