### ISSUE TITLE
meteo-concept/hcaptcha-bundle dev-master requires psr/http-factory-implementation

### ISSUE THREAD

**Issue by kyeno** [Meteo-Concept/hcaptcha-bundle#2]
...and it looks like `psr/http-factory-implementation` is an unknown package.
`php-fig/http-factory` is as close as it gets.

**Comment by lgeorget** [comment]
Hello !

Yes, this is actually a virtual package, so you have to chose a real implementation to satisfy the dependency (see this blog post for instance https://alanstorm.com/composer-virtual-packages/).

For Symfony  4 and 5, you can use symfony/http-client. For Symfony 3, you can use guzzlehttp/guzzle.

Virtual dependencies are not handled very cleverly by composer yet, but there are proposals to fix that... like https://github.com/composer/composer/issues/4535

**Comment by lgeorget** [comment]
Oh, for the http-factory, you need to install nyholm/psr7 by the way, the others are for the http-client.
