### ISSUE TITLE
PHP 8 compatibility 

### ISSUE THREAD

**Issue by Gerben321** [Meteo-Concept/hcaptcha-bundle#4]
Sorry if this is not the place, but I've updated my website to PHP 8 and got everything over to Symfony 5.2 including all packages, except for this one. For now I've resorted to reCaptcha, but I really don't want to use Google junk, and it's working poorly.

Anyway, would it be much trouble to update the package to support PHP 8? Would be great!

**Comment by lgeorget** [comment]
Hello!
This is certainly an objective of this package to support PHP8. It's probable that the package is already compatible with PHP8 actually. I'm going to update the composer.json and test how it goes.

**Comment by lgeorget** [comment]
So as I thought, nothing actually needed to be done to ensure compatibility with PHP8.0. All tests give green light. I've released a new major version, 2.0, becasue I also dropped support for PHP7.1.

**Comment by Gerben321** [comment]
Amazing! That's what I hoped. I'll go try it out right now, thanks!
