### ISSUE TITLE
little typo in the doc

### ISSUE THREAD

**Issue by NodokaMurmevent** [Meteo-Concept/hcaptcha-bundle#5]
in https://github.com/Meteo-Concept/hcaptcha-bundle#configuration

you write HCAPT**A**CHA_SECRET instead of  HCAPTCHA_SECRET

otherwise everything is perfect, your bundle is easy and quick to use. he his perfect !

**Comment by lgeorget** [comment]
Oh good catch, thank you! Closed by 57692fff13b094cb359f068f64e2806220493ecc
